language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - composer install
    - php .travis.php

script:
    - export $(cat .travis.env.sh | xargs) && php vendor/bin/phpunit -v
